kind: Service
apiVersion: v1
metadata:
  name: train-schedule-web
  labels:
    app: train-schedule-web
spec:
  type: LoadBalancer
  selector:
    app: train-schedule-web
  ports:
  - name: web
    port: 30001
    targetPort: 30001

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-web
  labels:
    app: train-schedule-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-web
  template:
    metadata:
      labels:
        app: train-schedule-web
    spec:
      containers:
      - name: train-schedule-web
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 30001
          name: train-schedule-web
